### PR TITLE
tee: imx8mp: allow to override the BL32 base address

### PR DESCRIPTION
**Pull request by fboudra**
Similarly to the imx8mm platform, allow to override the tee load address (BL32). It allows to use imx-mkimage for other i.MX8M Plus based boards. For instance, the hardcoded value doesn't work out for Toradex imx8mp-verdin SoM which comes in 1, 2, 4 and 8 GiB versions.

### CODE REVIEW

**Comment by fboudra** [comment]
@MrVan

**Comment by fboudra** [comment]
@cecannon7 @abelvesa ping, where can we submit patches so they can be reviewed and released for upcoming releases? thanks

**Comment by fboudra** [comment]
https://community.nxp.com/t5/i-MX-Processors/imx-mkimage-imx8mp-allow-to-override-the-BL32-base-address/m-p/1844938#M222374

and https://support.nxp.com/s/case/5002p00002xWcd8AAC/imxmkimage-imx8mp-allow-to-override-the-bl32-base-address

**Comment by MrVan** [comment]
@fboudra sadly, this repo is just for NXP SW release, not accept PR. I will pick up your patch inside NXP. Thanks for your contribution

**Comment by MrVan** [comment]
@fboudra Your patch has been checked in to NXP internal repo, you will see it in NXP Q2 release in July.

**Comment by fboudra** [comment]
Closing per the previous comment:
> patch has been checked in to NXP internal repo, you will see it in NXP Q2 release in July.

**Pull request closed without merging**
